// EXERCISE:
// You can write all the code natively (for cycles and such) or you can use some advanced functions which JS arrays provides in case you see them fit
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
// There can be multiple solutions to each task, solve it as you see fit.
// You will work with array `numbers` which will be generated by code (code below) in every task.
// Write these functions:

// This block generates array with random length with values between 1-100
let numbers = [];
const length = Math.ceil(Math.random() * 10) + 5;
for (let i = 0; i < length; i = i + 1) {
  numbers.push(Math.ceil(Math.random() * 100));
}

// a) Function which will print to console a whole array
const printArray = (numbers) => {
  // Your code:
 numbers.forEach((element) => console.log(element))
}
printArray(numbers)
// b) Function which will print to console the length of array
const printLength = (numbers) => {
  // Your code:
 console.log(`Length of array: ${numbers.length}`)
};
printLength(numbers)

// c) Function which will print to console the first element of array
const printFirstItem = (numbers) => {
  // Your code:
    console.log(`First item: ${numbers[0]}`)
};
printFirstItem(numbers)

// d) Function which will print to console the last element
const printLastItem = (numbers) => {
  // Your code:
    console.log(`Last item: ${numbers[numbers.length - 1]}`)

};
printLastItem(numbers)
// e) Function which will print to console the largest number (You can check Math functions)
const printLargestItem = (numbers) => {
  // Your code:
    console.log(`Largest item: ${Math.max(...numbers)}`)
};
printLargestItem(numbers)

// f) Function which will print to console the smallest number (You can check Math functions)
const printSmallestItem = (numbers) => {
  // Your code:
    console.log(`Smallest item: ${Math.min(...numbers)}`)
};
printSmallestItem(numbers)
// g) Function which will print to console the sum of all numbers in array (You can check reduce function)
const printSum = (numbers) => {
  // Your code:
    let sum = 0
    let reducer = numbers.reduce((currentSum, currentElement) => currentSum + currentElement, sum)
    console.log(`Sum of items: ${reducer}`)
};
printSum(numbers)
// h) Function which will print to console the difference between the largest and the smallest number (You can check Math functions)
const printSALDifference = (numbers) => {
  // Your code:
    let max = Math.max(...numbers)
    let min = Math.min(...numbers)
    console.log(`Difference between largest and smallest number: ${max - min}`)
};
printSALDifference(numbers)
// i) Function which will print to console the average of all numbers (You can check reduce function)
const printAverage = (numbers) => {
  // Your code:
    let sum = 0
    let reducer = numbers.reduce((currentSum, currentElement) => currentSum + currentElement, sum)
    console.log(`Average of all items: ${reducer / numbers.length}`)
};
printAverage(numbers)
// j) Function which will print to console the index of largest number (You can check Math functions)
const printLargestIndex = (numbers) => {
  // Your code:
    let max = Math.max(...numbers)

    console.log(`Index of largest item: ${numbers.indexOf(max)}`)

};
printLargestIndex(numbers)
// k) Function which will print to console the even numbers (not the array of even numbers),
// if array doesn't contain any even number, show text "Even number isn't in array"
const printEvenNums = (numbers) => {
  // Your code:
    console.log("Even numbers:")
    let hasEven = false
    numbers.forEach((element) => {
        if(element % 2 === 0) {
            console.log(element)
            hasEven = true
        }
    })
    if (!hasEven){
        console.log("Even number isn't in array")
    }

};

printEvenNums(numbers)

// l) Function which will multiple by 2 every number in array and print the array to console
// Example: printNumsMultipliedBy2([1,2,3]) -> [2,4,6]
const printNumsMultipliedBy2 = (numbers) => {

  // Your code:
    let multiplies = []
    console.log("Multiplied numbers:")
    numbers.forEach((element) => {
        multiplies.push(element * 2)
    })
    console.log(multiplies)

};
printNumsMultipliedBy2(numbers)